In [3]:
import numpy as np

In [ ]:
Multi-DImensional Array

In [4]:
AAA=np.array([[[10,20,30]]])

In [5]:
AAA[0][0][0]

10

In [6]:
AAA[0][0]

array([10, 20, 30])

In [7]:
AAA.dtype

dtype('int32')

In [8]:
AAA.shape

(1, 1, 3)

In [11]:
AAA.size # Row into column value

3

In [12]:
AAA.ndim

3

In [13]:
AA=np.array([[10,20,30],[23,55,15]])

In [15]:
AA.shape

(2, 3)

In [16]:
AA.size

6

In [18]:
AA[0][0]

10

In [20]:
AA[0]

array([10, 20, 30])

In [21]:
A=np.array([10,20,30])

In [22]:
A

array([10, 20, 30])

In [23]:
A[0]

10

In [24]:
A.shape

(3,)

In [25]:
A.size

3

In [50]:
BB=np.zeros((2,3,2))


In [29]:
AA=np.array([[10,20,30,],[23,55,15]],dtype=float)

In [30]:
AA

array([[10., 20., 30.],
       [23., 55., 15.]])

In [37]:
LLL=(
    
    [
      
        [
            [10,20,30,40],[8,8,2,1],[1,1,1,2]
        ],
        
        
        [
            [9,9,2,39],[1,2,3,3],[0,0,3,2]
        ],
        
        
        [
            [12,33,22,1],[22,1,22,2],[0,2,3,1]
        ],
    ]
    
    )

In [39]:
AAA1=np.array(
    
    [
      
        [
            [10,20,30,40],[8,8,2,1],[1,1,1,2]
        ],
        
        
        [
            [9,9,2,39],[1,2,3,3],[0,0,3,2]
        ],
        
        
        [
            [12,33,22,1],[22,1,22,2],[0,2,3,1]
        ],
    ]
    
    )

In [40]:
AAA1

array([[[10, 20, 30, 40],
        [ 8,  8,  2,  1],
        [ 1,  1,  1,  2]],

       [[ 9,  9,  2, 39],
        [ 1,  2,  3,  3],
        [ 0,  0,  3,  2]],

       [[12, 33, 22,  1],
        [22,  1, 22,  2],
        [ 0,  2,  3,  1]]])

In [41]:
AAA1.shape

(3, 3, 4)

In [42]:
AAA1.ndim

3

In [43]:
AAA1.shape

(3, 3, 4)

In [44]:
AAA1[2][2][3]

1

by default numpy is <font size=6><b>.,</b></font> format even if it is integer

In [47]:
AAAe=np.exp(AAA)

In [48]:
np.set_printoptions(suppress=True)

In [49]:
AAAe

array([[[2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17],
        [2.98095799e+03, 2.98095799e+03, 7.38905610e+00, 2.71828183e+00],
        [2.71828183e+00, 2.71828183e+00, 2.71828183e+00, 7.38905610e+00]],

       [[8.10308393e+03, 8.10308393e+03, 7.38905610e+00, 8.65934004e+16],
        [2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 2.00855369e+01],
        [1.00000000e+00, 1.00000000e+00, 2.00855369e+01, 7.38905610e+00]],

       [[1.62754791e+05, 2.14643580e+14, 3.58491285e+09, 2.71828183e+00],
        [3.58491285e+09, 2.71828183e+00, 3.58491285e+09, 7.38905610e+00],
        [1.00000000e+00, 7.38905610e+00, 2.00855369e+01, 2.71828183e+00]]])

In [51]:
BB

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
np.sqrt(AAA)

array([[[3.16227766, 4.47213595, 5.47722558, 6.32455532],
        [2.82842712, 2.82842712, 1.41421356, 1.        ],
        [1.        , 1.        , 1.        , 1.41421356]],

       [[3.        , 3.        , 1.41421356, 6.244998  ],
        [1.        , 1.41421356, 1.73205081, 1.73205081],
        [0.        , 0.        , 1.73205081, 1.41421356]],

       [[3.46410162, 5.74456265, 4.69041576, 1.        ],
        [4.69041576, 1.        , 4.69041576, 1.41421356],
        [0.        , 1.41421356, 1.73205081, 1.        ]]])

In [53]:
AAA.sum()

318

In [54]:
AAA.min()

0

In [55]:
AAA.max()

40

In [57]:
AAA.mean() #of all values

8.833333333333334

In [59]:
np.median(AAA)

2.5

In [61]:
np.std(AAA) #Std deviation

11.49758428733812

In [63]:
np.median(b_linspace2)

NameError: name 'b_linspace2' is not defined